### ISSUE TITLE
Please bump version of 'fast' that node-moray depends on

### ISSUE THREAD

**Issue by aglasgall** [joyent/node-moray#1]
The version currently pinned in node-moray's package.json explodes messily if the system it's running on doesn't support dtrace; newer versions replace the dtrace functions with stubs if the system doesn't have it. I ran into this while trying to work on sdc-adminui on my Linux system (pointed at a CoaL running in vmware workstation). This happens to work on a Mac because OS X has dtrace, but not on other host platforms.

**Comment by lloydde** [comment]
I suspect the fix to node-fast, came when @pfmooney updated the node-dtrace-provider to 0.3.0 in mcavage/node-fast@784741e6eec91ae9bae7c2e3b138be798e0ce37e

**Comment by aglasgall** [comment]
On Fri, Apr 10, 2015 at 12:07:23PM -0700, Lloyd Dewolf wrote:
> I suspect the fix to node-fast, came when @pfmooney updated the node-dtrace-provider to 0.3.0 in mcavage/node-fast@784741e6eec91ae9bae7c2e3b138be798e0ce37e 
>

No, it's not just the newer node-dtrace-provider, it's a change to lib/protocol/dtrace.js Looks like mcavage/node-fast@6018c83af39c9f54877328e0b3d7aa07970926f8 ?

**Comment by lloydde** [comment]
@aglasgall that makes more sense, sorry.

**Comment by davepacheco** [comment]
I'm not sure if this is still relevant, but this would have been fixed with the major rewrite a few months ago.
