### ISSUE TITLE
should use a priority-queue to assign connection.

### ISSUE THREAD

**Issue by timkordas** [joyent/node-moray#4]
The comment in pool.js notes that it would be smarter to use a priority-queue.

I believe that use of random assignment can result is an odd sort of positive-feedback loop:

Randomly picking Moray servers works when their response times are all uniform; but small differences in response times, (especially with bursty workloads) can end up assigning to much work to the slowest server(s).

In cases where the server performance is partly dictated by the amount of work assigned (ie having a backlog slows down responses), we end up with a positive feedback loop where once one server has a backlog, it struggles to recover because new work is assigned uniformly.

An exacerbating factor is that a server may get "unlucky" and be assigned work which is intrinsically more expensive (either because it involves more computation or has greater lock contention further down the stack).

Using a priority queue based on number of outstanding requests may not be perfectly fair (all requests aren't equally costly, see above) but definitely avoids the "piling on" effect where a slow server gets assigned the same amount of work as an idle server.

**Comment by jclulow** [comment]
Moved into JIRA as [MORAY-452](https://smartos.org/bugview/MORAY-452).
